jobs:
  # Basic config API here: https://jenkinsci.github.io/job-dsl-plugin/#
  # Most of the time you should look at your own live instance due to runtime introspection
  - script: |
      organizationFolder("bradschwartz") {
        organizations {
          github {
            credentialsId("")
            repoOwner("bradschwartz")

            traits {
              gitHubBranchDiscovery {
                strategyId(1)
              }
            }
          }
        }
        properties {
          suppressFolderAutomaticTriggering {
            branches("main|PR-\\d+")
            strategy("INDEXING")
          }
        }
      }
